#!/usr/bin/env python
"""Strip last30days engine stdout noise from the HTML brief output.

When `last30days.py --emit=html` is invoked, the engine writes planning +
search logs + quality_nudge text to stdout, THEN the HTML body. A simple
`>` redirect captures all of it. Browsers render the noise as plain text
before the HTML, breaking the visual design.

This script reads the file, finds the first `<!DOCTYPE html>`, and rewrites
the file with only the HTML body (plus a UTF-8 BOM-free header for safety).

Usage:
    python extract_html_noise.py <path_to_html_file>

Or as a module:
    from extract_html_noise import strip_noise
    strip_noise(Path("brief.html"))
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

DOCTYPE_PATTERN = re.compile(r"<!DOCTYPE\s+html", re.IGNORECASE)


def strip_noise(html_path: Path) -> tuple[int, int]:
    """Strip engine stdout noise from the front of an HTML brief.

    Reads the file, finds the first `<!DOCTYPE html>`, writes only the HTML
    body to disk (overwriting the original).

    Returns:
        (original_size, cleaned_size) byte counts.
    """
    raw = html_path.read_text(encoding="utf-8", errors="replace")
    match = DOCTYPE_PATTERN.search(raw)
    if not match:
        raise ValueError(
            f"No <!DOCTYPE html> marker found in {html_path}. "
            "Was the HTML brief generated by last30days --emit=html?"
        )
    cleaned = raw[match.start():].lstrip()
    html_path.write_text(cleaned, encoding="utf-8")
    return len(raw), len(cleaned)


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: python extract_html_noise.py <html_file>", file=sys.stderr)
        return 2
    path = Path(sys.argv[1])
    if not path.exists():
        print(f"File not found: {path}", file=sys.stderr)
        return 1
    try:
        before, after = strip_noise(path)
        print(f"Stripped: {before} -> {after} bytes ({before - after} bytes of stdout noise removed)")
        return 0
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
